id: IF50A3C5C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:23:21+00:00'
last_modified: '2022-06-16T05:39:04.881173+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24859
  title: ལེགས་འགྲུབ་ཡོང་བ་ཇི་ལྟར་བྱེད། རི་མོའི་ལམ་ནས་པིར་ཀའི་ཚིའི་སྐོར་གླེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B000:
      image_group_id: I1KG24861
      title: Volume 1 of legs 'grub yong ba ji ltar byed/_ri mo'i lam nas pir ka'i
        tshi'i skor gleng ba/
      total_pages: 188
      order: 1
      base_file: B000.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
